server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://uz57kpyuwmlsvuci:NVvMooV75aF03Xpx1r8s@brvgaxpwlsxeppdppjeo-mysql.services.clever-cloud.com:3306/brvgaxpwlsxeppdppjeo
    username: brvgaxpwlsxeppdppjeo
    password: NVvMooV75aF03Xpx1r8s
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: c2ltcGxlLWVjb21tZXJjZS13aXNobGlzdC1zZWNyZXQta2V5LWZvci1oczI1Ni0yMDI2
  expiration-ms: 86400000